import type { UnitKey } from './units.ts';

/**
 * Mampffred-Lebensmittelkatalog v1.
 *
 * Eigene, handgepflegte Zuordnung alltagstauglicher Zutaten zu
 * Ladenkategorie, Haushaltsmengen, Kaufeinheiten und einem BLS-4.0-Code.
 * Stück- und Löffelgewichte sind typische essbare Mengen (gerundet,
 * gegengeprüft an USDA FoodData Central, CC0). Packungsgrößen sind
 * generische, im deutschen Handel übliche Größen.
 */

export type AisleId =
  | 'obst-gemuese'
  | 'brot'
  | 'kuehlregal'
  | 'fleisch-fisch'
  | 'veggie'
  | 'trocken'
  | 'konserven'
  | 'backen'
  | 'wuerzen'
  | 'fruehstueck'
  | 'tiefkuehl'
  | 'getraenke'
  | 'drogerie'
  | 'sonstiges';

export type CatalogSell =
  /** Stückware, wird auf ganze Stück aufgerundet (braucht g.stueck). */
  | 'piece'
  /** Lose Ware nach Gewicht. */
  | 'weight'
  /** Packung: Größe in g, ml oder als Stückzahl (mit g.stueck). */
  | { unit: UnitKey; g?: number; ml?: number; pieces?: number };

export type CatalogEntry = {
  id: string;
  name: string;
  plural?: string;
  syn?: string[];
  aisle: AisleId;
  bls?: string;
  /** Gramm je Einheit. */
  g?: Partial<Record<UnitKey, number>>;
  /** Gramm je Milliliter. */
  density?: number;
  sell?: CatalogSell;
  pantry?: 'often';
  /** false: mengenmäßig vernachlässigbar (Salz, Gewürze, Wasser). */
  nutrition?: false;
  /** false: wird nie eingekauft (Wasser). */
  shopping?: false;
};

export const FOOD_CATALOG_VERSION = '2026-10-01';

export const FOOD_CATALOG: CatalogEntry[] = [
  // Obst & Gemüse
  {
    id: 'tomate',
    name: 'Tomate',
    plural: 'Tomaten',
    syn: [
      'Rispentomate',
      'Rispentomaten',
      'Strauchtomate',
      'Strauchtomaten',
      'Romatomate',
      'Romatomaten',
    ],
    aisle: 'obst-gemuese',
    bls: 'G561100',
    g: { stueck: 100, scheibe: 15 },
    sell: 'piece',
  },
  {
    id: 'cherrytomate',
    name: 'Cherrytomate',
    plural: 'Cherrytomaten',
    syn: [
      'Kirschtomate',
      'Kirschtomaten',
      'Cocktailtomate',
      'Cocktailtomaten',
      'Datteltomate',
      'Datteltomaten',
      'Cherry-Tomaten',
      'Cherry Tomaten',
      'Snacktomaten',
    ],
    aisle: 'obst-gemuese',
    bls: 'G561100',
    g: { stueck: 15, handvoll: 80 },
    sell: { unit: 'schale', g: 250 },
  },
  {
    id: 'fleischtomate',
    name: 'Fleischtomate',
    plural: 'Fleischtomaten',
    syn: ['Ochsenherztomate', 'Ochsenherztomaten'],
    aisle: 'obst-gemuese',
    bls: 'G561100',
    g: { stueck: 250, scheibe: 30 },
    sell: 'piece',
  },
  {
    id: 'gurke',
    name: 'Gurke',
    plural: 'Gurken',
    syn: [
      'Salatgurke',
      'Salatgurken',
      'Schlangengurke',
      'Minigurke',
      'Minigurken',
    ],
    aisle: 'obst-gemuese',
    bls: 'G520100',
    g: { stueck: 400, scheibe: 8 },
    sell: 'piece',
  },
  {
    id: 'paprika',
    name: 'Paprika',
    plural: 'Paprika',
    syn: [
      'Paprikaschote',
      'Paprikaschoten',
      'rote Paprika',
      'gelbe Paprika',
      'grüne Paprika',
      'Spitzpaprika',
      'Gemüsepaprika',
      'Paprika rot',
      'Paprika gelb',
    ],
    aisle: 'obst-gemuese',
    bls: 'G543100',
    g: { stueck: 160 },
    sell: 'piece',
  },
  {
    id: 'zucchini',
    name: 'Zucchini',
    plural: 'Zucchini',
    syn: ['Zucchinis', 'Zucchino'],
    aisle: 'obst-gemuese',
    bls: 'G582100',
    g: { stueck: 250 },
    sell: 'piece',
  },
  {
    id: 'aubergine',
    name: 'Aubergine',
    plural: 'Auberginen',
    aisle: 'obst-gemuese',
    bls: 'G510100',
    g: { stueck: 300 },
    sell: 'piece',
  },
  {
    id: 'zwiebel',
    name: 'Zwiebel',
    plural: 'Zwiebeln',
    syn: [
      'Speisezwiebel',
      'Speisezwiebeln',
      'Gemüsezwiebel',
      'gelbe Zwiebel',
      'weiße Zwiebel',
    ],
    aisle: 'obst-gemuese',
    bls: 'G480100',
    g: { stueck: 90, el: 10 },
    sell: 'piece',
  },
  {
    id: 'rote-zwiebel',
    name: 'Rote Zwiebel',
    plural: 'Rote Zwiebeln',
    syn: ['rote Zwiebeln', 'Lila Zwiebel'],
    aisle: 'obst-gemuese',
    bls: 'G480100',
    g: { stueck: 90, el: 10 },
    sell: 'piece',
  },
  {
    id: 'schalotte',
    name: 'Schalotte',
    plural: 'Schalotten',
    aisle: 'obst-gemuese',
    bls: 'G485100',
    g: { stueck: 25 },
    sell: 'piece',
  },
  {
    id: 'fruehlingszwiebel',
    name: 'Frühlingszwiebel',
    plural: 'Frühlingszwiebeln',
    syn: ['Lauchzwiebel', 'Lauchzwiebeln'],
    aisle: 'obst-gemuese',
    bls: 'G482100',
    g: { stueck: 15, bund: 120, stange: 15 },
    sell: { unit: 'bund', g: 120 },
  },
  {
    id: 'knoblauch',
    name: 'Knoblauch',
    syn: [
      'Knoblauchzehe',
      'Knoblauchzehen',
      'Knoblauchknolle',
      'frischer Knoblauch',
    ],
    aisle: 'obst-gemuese',
    bls: 'G490100',
    g: { zehe: 4, stueck: 4, knolle: 50, tl: 4 },
    sell: { unit: 'knolle', g: 50 },
  },
  {
    id: 'lauch',
    name: 'Lauch',
    syn: ['Porree', 'Lauchstange', 'Lauchstangen'],
    aisle: 'obst-gemuese',
    bls: 'G470100',
    g: { stueck: 200, stange: 200 },
    sell: { unit: 'stange', g: 200 },
  },
  {
    id: 'moehre',
    name: 'Möhre',
    plural: 'Möhren',
    syn: ['Karotte', 'Karotten', 'Mohrrübe', 'Mohrrüben', 'Rübli'],
    aisle: 'obst-gemuese',
    bls: 'G620100',
    g: { stueck: 80 },
    sell: 'piece',
  },
  {
    id: 'kartoffel',
    name: 'Kartoffel',
    plural: 'Kartoffeln',
    syn: [
      'Drillinge',
      'festkochende Kartoffeln',
      'mehligkochende Kartoffeln',
      'vorwiegend festkochende Kartoffeln',
      'Frühkartoffeln',
      'Speisekartoffeln',
    ],
    aisle: 'obst-gemuese',
    bls: 'K110100',
    g: { stueck: 100 },
    sell: 'weight',
  },
  {
    id: 'suesskartoffel',
    name: 'Süßkartoffel',
    plural: 'Süßkartoffeln',
    syn: ['Batate', 'Bataten'],
    aisle: 'obst-gemuese',
    bls: 'K420100',
    g: { stueck: 300 },
    sell: 'piece',
  },
  {
    id: 'hokkaido',
    name: 'Hokkaido-Kürbis',
    plural: 'Hokkaido-Kürbisse',
    syn: [
      'Hokkaido',
      'Hokkaidokürbis',
      'Hokkaido Kürbis',
      'Kürbis',
      'Speisekürbis',
    ],
    aisle: 'obst-gemuese',
    bls: 'G581000',
    g: { stueck: 1000 },
    sell: 'piece',
  },
  {
    id: 'butternut',
    name: 'Butternut-Kürbis',
    plural: 'Butternut-Kürbisse',
    syn: ['Butternut', 'Butternutkürbis', 'Butternut Kürbis'],
    aisle: 'obst-gemuese',
    bls: 'G581100',
    g: { stueck: 1200 },
    sell: 'piece',
  },
  {
    id: 'brokkoli',
    name: 'Brokkoli',
    plural: 'Brokkoli',
    syn: ['Broccoli', 'Brokkoliröschen', 'Brokkolirösschen'],
    aisle: 'obst-gemuese',
    bls: 'G312100',
    g: { stueck: 500, kopf: 500 },
    sell: 'piece',
  },
  {
    id: 'blumenkohl',
    name: 'Blumenkohl',
    plural: 'Blumenkohl',
    syn: ['Blumenkohlröschen'],
    aisle: 'obst-gemuese',
    bls: 'G311100',
    g: { stueck: 800, kopf: 800 },
    sell: 'piece',
  },
  {
    id: 'kohlrabi',
    name: 'Kohlrabi',
    plural: 'Kohlrabi',
    aisle: 'obst-gemuese',
    bls: 'G331100',
    g: { stueck: 300 },
    sell: 'piece',
  },
  {
    id: 'spinat',
    name: 'Babyspinat',
    syn: ['Spinat', 'Blattspinat', 'frischer Spinat', 'Spinatblätter'],
    aisle: 'obst-gemuese',
    bls: 'G211100',
    g: { handvoll: 30 },
    sell: { unit: 'beutel', g: 200 },
  },
  {
    id: 'rucola',
    name: 'Rucola',
    syn: ['Rauke'],
    aisle: 'obst-gemuese',
    bls: 'G130100',
    g: { handvoll: 20, bund: 100 },
    sell: { unit: 'schale', g: 125 },
  },
  {
    id: 'feldsalat',
    name: 'Feldsalat',
    syn: ['Rapunzel'],
    aisle: 'obst-gemuese',
    bls: 'G104100',
    g: { handvoll: 20 },
    sell: { unit: 'schale', g: 150 },
  },
  {
    id: 'salat',
    name: 'Salat',
    plural: 'Salatköpfe',
    syn: [
      'Kopfsalat',
      'Blattsalat',
      'Salatkopf',
      'Salatblätter',
      'Salatblatt',
      'grüner Salat',
      'Pflücksalat',
      'Lollo Rosso',
    ],
    aisle: 'obst-gemuese',
    bls: 'G105100',
    g: { stueck: 300, kopf: 300, blatt: 15, handvoll: 25 },
    sell: 'piece',
  },
  {
    id: 'salatherz',
    name: 'Salatherz',
    plural: 'Salatherzen',
    syn: [
      'Romanasalat',
      'Romana',
      'Herzsalat',
      'Römersalat',
      'Mini-Romana',
      'Romana-Salatherzen',
    ],
    aisle: 'obst-gemuese',
    bls: 'G107100',
    g: { stueck: 150, blatt: 15 },
    sell: { unit: 'packung', pieces: 2 },
  },
  {
    id: 'eisbergsalat',
    name: 'Eisbergsalat',
    plural: 'Eisbergsalate',
    syn: ['Eisberg'],
    aisle: 'obst-gemuese',
    bls: 'G103100',
    g: { stueck: 500, kopf: 500 },
    sell: 'piece',
  },
  {
    id: 'champignon',
    name: 'Champignon',
    plural: 'Champignons',
    syn: [
      'Pilze',
      'Egerlinge',
      'braune Champignons',
      'weiße Champignons',
      'Champignons braun',
    ],
    aisle: 'obst-gemuese',
    bls: 'K701100',
    g: { stueck: 20, handvoll: 60 },
    sell: { unit: 'schale', g: 250 },
  },
  {
    id: 'kraeuterseitling',
    name: 'Kräuterseitling',
    plural: 'Kräuterseitlinge',
    syn: ['Seitlinge', 'Austernpilze', 'Austernpilz', 'Austernseitlinge'],
    aisle: 'obst-gemuese',
    bls: 'K740100',
    g: { stueck: 50 },
    sell: { unit: 'schale', g: 200 },
  },
  {
    id: 'spargel-gruen',
    name: 'Grüner Spargel',
    syn: ['grünen Spargel', 'Grünspargel'],
    aisle: 'obst-gemuese',
    bls: 'G450100',
    g: { stueck: 25, stange: 25 },
    sell: { unit: 'bund', g: 500 },
  },
  {
    id: 'spargel-weiss',
    name: 'Weißer Spargel',
    syn: ['Spargel', 'Bleichspargel', 'weißen Spargel', 'Spargelstangen'],
    aisle: 'obst-gemuese',
    bls: 'G450100',
    g: { stueck: 60, stange: 60 },
    sell: 'weight',
  },
  {
    id: 'zuckerschote',
    name: 'Zuckerschote',
    plural: 'Zuckerschoten',
    syn: ['Zuckererbsen', 'Kaiserschoten', 'Zuckererbsenschoten'],
    aisle: 'obst-gemuese',
    bls: 'G761100',
    g: { stueck: 5, handvoll: 50 },
    sell: { unit: 'schale', g: 150 },
  },
  {
    id: 'gruene-bohnen',
    name: 'Grüne Bohnen',
    syn: ['Prinzessbohnen', 'Buschbohnen', 'Keniabohnen', 'frische Bohnen'],
    aisle: 'obst-gemuese',
    bls: 'G710100',
    g: { handvoll: 60 },
    sell: 'weight',
  },
  {
    id: 'rotkohl',
    name: 'Rotkohl',
    syn: ['Blaukraut', 'Rotkraut'],
    aisle: 'obst-gemuese',
    bls: 'G341100',
    g: { stueck: 1000, kopf: 1000 },
    sell: 'piece',
  },
  {
    id: 'weisskohl',
    name: 'Weißkohl',
    syn: ['Weißkraut'],
    aisle: 'obst-gemuese',
    bls: 'G342100',
    g: { stueck: 1200, kopf: 1200 },
    sell: 'piece',
  },
  {
    id: 'spitzkohl',
    name: 'Spitzkohl',
    aisle: 'obst-gemuese',
    bls: 'G344100',
    g: { stueck: 800, kopf: 800 },
    sell: 'piece',
  },
  {
    id: 'rote-bete',
    name: 'Rote Bete',
    syn: [
      'Rote Beete',
      'Rote Rüben',
      'Rote Rübe',
      'Rote Bete vorgekocht',
      'Rote Bete gekocht',
      'Rote-Bete-Knollen',
    ],
    aisle: 'obst-gemuese',
    bls: 'G613132',
    g: { stueck: 100, knolle: 100 },
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'sellerie',
    name: 'Knollensellerie',
    syn: ['Sellerie', 'Sellerieknolle', 'Selleriewurzel'],
    aisle: 'obst-gemuese',
    bls: 'G660100',
    g: { stueck: 500, knolle: 500 },
    sell: 'piece',
  },
  {
    id: 'staudensellerie',
    name: 'Staudensellerie',
    syn: [
      'Stangensellerie',
      'Selleriestange',
      'Selleriestangen',
      'Bleichsellerie',
    ],
    aisle: 'obst-gemuese',
    bls: 'G660100',
    g: { stueck: 40, stange: 40 },
    sell: { unit: 'bund', g: 500 },
  },
  {
    id: 'fenchel',
    name: 'Fenchel',
    plural: 'Fenchelknollen',
    syn: ['Fenchelknolle', 'Gemüsefenchel'],
    aisle: 'obst-gemuese',
    bls: 'G430100',
    g: { stueck: 250, knolle: 250 },
    sell: 'piece',
  },
  {
    id: 'radieschen',
    name: 'Radieschen',
    plural: 'Radieschen',
    aisle: 'obst-gemuese',
    bls: 'G691100',
    g: { stueck: 10, bund: 150 },
    sell: { unit: 'bund', g: 150 },
  },
  {
    id: 'ingwer',
    name: 'Ingwer',
    syn: ['Ingwerwurzel', 'frischer Ingwer'],
    aisle: 'obst-gemuese',
    bls: 'R211200',
    g: { stueck: 20, tl: 3, el: 8 },
    sell: { unit: 'stueck', g: 50 },
  },
  {
    id: 'chili',
    name: 'Chilischote',
    plural: 'Chilischoten',
    syn: ['Chili', 'Peperoni', 'rote Chili', 'frische Chili', 'Peperoncino'],
    aisle: 'obst-gemuese',
    bls: 'G554100',
    g: { stueck: 10 },
    sell: 'piece',
  },
  {
    id: 'suppengemuese',
    name: 'Suppengemüse',
    syn: ['Suppengrün', 'Suppenbund'],
    aisle: 'obst-gemuese',
    bls: 'G620100',
    g: { bund: 500 },
    sell: { unit: 'bund', g: 500 },
  },
  {
    id: 'avocado',
    name: 'Avocado',
    plural: 'Avocados',
    aisle: 'obst-gemuese',
    bls: 'F502100',
    g: { stueck: 150 },
    sell: 'piece',
  },
  {
    id: 'petersilie',
    name: 'Petersilie',
    syn: [
      'glatte Petersilie',
      'krause Petersilie',
      'Blattpetersilie',
      'frische Petersilie',
    ],
    aisle: 'obst-gemuese',
    bls: 'G250100',
    g: { bund: 30, el: 4, handvoll: 15 },
    sell: { unit: 'bund', g: 30 },
  },
  {
    id: 'basilikum',
    name: 'Basilikum',
    syn: ['frisches Basilikum', 'Basilikumblätter'],
    aisle: 'obst-gemuese',
    bls: 'G061000',
    g: { bund: 30, topf: 30, blatt: 0.5, handvoll: 10, el: 2 },
    sell: { unit: 'topf', g: 30 },
  },
  {
    id: 'schnittlauch',
    name: 'Schnittlauch',
    aisle: 'obst-gemuese',
    bls: 'G081100',
    g: { bund: 25, el: 3 },
    sell: { unit: 'bund', g: 25 },
  },
  {
    id: 'koriander',
    name: 'Koriander',
    syn: ['Koriandergrün', 'frischer Koriander'],
    aisle: 'obst-gemuese',
    nutrition: false,
    g: { bund: 30 },
    sell: { unit: 'bund', g: 30 },
  },
  {
    id: 'dill',
    name: 'Dill',
    aisle: 'obst-gemuese',
    nutrition: false,
    g: { bund: 20 },
    sell: { unit: 'bund', g: 20 },
  },
  {
    id: 'minze',
    name: 'Minze',
    syn: ['Pfefferminze', 'frische Minze'],
    aisle: 'obst-gemuese',
    nutrition: false,
    g: { bund: 20 },
    sell: { unit: 'bund', g: 20 },
  },
  {
    id: 'thymian',
    name: 'Thymian',
    syn: ['frischer Thymian', 'Thymianzweige'],
    aisle: 'obst-gemuese',
    nutrition: false,
    g: { zweig: 1, bund: 15 },
    sell: { unit: 'bund', g: 15 },
  },
  {
    id: 'rosmarin',
    name: 'Rosmarin',
    syn: ['frischer Rosmarin', 'Rosmarinzweige'],
    aisle: 'obst-gemuese',
    nutrition: false,
    g: { zweig: 1, bund: 15 },
    sell: { unit: 'bund', g: 15 },
  },
  {
    id: 'kraeuter',
    name: 'Kräuter',
    syn: ['frische Kräuter', 'gemischte Kräuter', 'Kräuter nach Wahl'],
    aisle: 'obst-gemuese',
    nutrition: false,
    g: { bund: 30, handvoll: 15 },
    sell: { unit: 'bund', g: 30 },
  },
  {
    id: 'apfel',
    name: 'Apfel',
    plural: 'Äpfel',
    aisle: 'obst-gemuese',
    bls: 'F110100',
    g: { stueck: 150 },
    sell: 'piece',
  },
  {
    id: 'birne',
    name: 'Birne',
    plural: 'Birnen',
    aisle: 'obst-gemuese',
    bls: 'F130100',
    g: { stueck: 170 },
    sell: 'piece',
  },
  {
    id: 'banane',
    name: 'Banane',
    plural: 'Bananen',
    aisle: 'obst-gemuese',
    bls: 'F503100',
    g: { stueck: 120 },
    sell: 'piece',
  },
  {
    id: 'zitrone',
    name: 'Zitrone',
    plural: 'Zitronen',
    syn: ['Bio-Zitrone', 'Bio-Zitronen', 'unbehandelte Zitrone'],
    aisle: 'obst-gemuese',
    bls: 'F601100',
    g: { stueck: 100 },
    sell: 'piece',
  },
  {
    id: 'limette',
    name: 'Limette',
    plural: 'Limetten',
    syn: ['Bio-Limette', 'Limone'],
    aisle: 'obst-gemuese',
    bls: 'F602100',
    g: { stueck: 60 },
    sell: 'piece',
  },
  {
    id: 'orange',
    name: 'Orange',
    plural: 'Orangen',
    syn: ['Apfelsine', 'Apfelsinen', 'Bio-Orange'],
    aisle: 'obst-gemuese',
    bls: 'F603100',
    g: { stueck: 200 },
    sell: 'piece',
  },
  {
    id: 'mango',
    name: 'Mango',
    plural: 'Mangos',
    aisle: 'obst-gemuese',
    bls: 'F516100',
    g: { stueck: 300 },
    sell: 'piece',
  },
  {
    id: 'kiwi',
    name: 'Kiwi',
    plural: 'Kiwis',
    aisle: 'obst-gemuese',
    bls: 'F514100',
    g: { stueck: 75 },
    sell: 'piece',
  },
  {
    id: 'ananas',
    name: 'Ananas',
    plural: 'Ananas',
    syn: ['frische Ananas'],
    aisle: 'obst-gemuese',
    bls: 'F501100',
    g: { stueck: 1000 },
    sell: 'piece',
  },
  {
    id: 'weintrauben',
    name: 'Weintrauben',
    syn: ['Trauben', 'Tafeltrauben', 'Weintraube'],
    aisle: 'obst-gemuese',
    bls: 'F310100',
    g: { handvoll: 80 },
    sell: { unit: 'schale', g: 500 },
  },
  {
    id: 'erdbeere',
    name: 'Erdbeere',
    plural: 'Erdbeeren',
    aisle: 'obst-gemuese',
    bls: 'F301100',
    g: { stueck: 15, handvoll: 80 },
    sell: { unit: 'schale', g: 500 },
  },
  {
    id: 'himbeere',
    name: 'Himbeere',
    plural: 'Himbeeren',
    aisle: 'obst-gemuese',
    bls: 'F302100',
    g: { handvoll: 60 },
    sell: { unit: 'schale', g: 125 },
  },
  {
    id: 'heidelbeere',
    name: 'Heidelbeere',
    plural: 'Heidelbeeren',
    syn: ['Blaubeere', 'Blaubeeren'],
    aisle: 'obst-gemuese',
    bls: 'F304100',
    g: { handvoll: 60 },
    sell: { unit: 'schale', g: 125 },
  },
  {
    id: 'beeren',
    name: 'Beeren',
    syn: ['Beerenmischung', 'gemischte Beeren', 'frische Beeren', 'Beerenobst'],
    aisle: 'obst-gemuese',
    bls: 'F092100',
    g: { handvoll: 60 },
    sell: { unit: 'schale', g: 250 },
  },

  // Brot & Backwaren
  {
    id: 'toastbrot',
    name: 'Toastbrot',
    syn: [
      'Toast',
      'Toastscheiben',
      'Toastscheibe',
      'Buttertoast',
      'Sandwichtoast',
      'Weizentoast',
      'Toastbrotscheiben',
    ],
    aisle: 'brot',
    bls: 'B314000',
    g: { scheibe: 25, stueck: 25 },
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'vollkorntoast',
    name: 'Vollkorntoast',
    syn: ['Vollkorntoastbrot', 'Vollkorn-Toast'],
    aisle: 'brot',
    bls: 'B111200',
    g: { scheibe: 28, stueck: 28 },
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'brot',
    name: 'Brot',
    plural: 'Brote',
    syn: [
      'Mischbrot',
      'Bauernbrot',
      'Roggenmischbrot',
      'Brotscheiben',
      'Landbrot',
      'Graubrot',
      'Sauerteigbrot',
    ],
    aisle: 'brot',
    bls: 'B271000',
    g: { scheibe: 45, stueck: 750 },
    sell: 'piece',
  },
  {
    id: 'vollkornbrot',
    name: 'Vollkornbrot',
    syn: ['Vollkornbrotscheiben', 'Roggenvollkornbrot'],
    aisle: 'brot',
    bls: 'B101000',
    g: { scheibe: 50 },
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'broetchen',
    name: 'Brötchen',
    plural: 'Brötchen',
    syn: [
      'Semmel',
      'Semmeln',
      'Weizenbrötchen',
      'Aufbackbrötchen',
      'Schrippe',
      'Schrippen',
      'Brötchen zum Aufbacken',
    ],
    aisle: 'brot',
    bls: 'B511000',
    g: { stueck: 55 },
    sell: 'piece',
  },
  {
    id: 'baguette',
    name: 'Baguette',
    plural: 'Baguettes',
    syn: ['Baguettebrot', 'Stangenweißbrot'],
    aisle: 'brot',
    bls: 'B781200',
    g: { stueck: 250, scheibe: 15 },
    sell: 'piece',
  },
  {
    id: 'ciabatta',
    name: 'Ciabatta',
    plural: 'Ciabatta',
    syn: ['Ciabattabrot'],
    aisle: 'brot',
    bls: 'B781200',
    g: { stueck: 300, scheibe: 20 },
    sell: 'piece',
  },
  {
    id: 'burger-buns',
    name: 'Burger-Brötchen',
    plural: 'Burger-Brötchen',
    syn: [
      'Burger-Buns',
      'Burger Buns',
      'Burgerbrötchen',
      'Burgerbuns',
      'Brioche-Buns',
      'Hamburgerbrötchen',
      'Burger-Bun',
    ],
    aisle: 'brot',
    bls: 'B511000',
    g: { stueck: 70 },
    sell: { unit: 'packung', pieces: 4 },
  },
  {
    id: 'wraps',
    name: 'Wrap',
    plural: 'Wraps',
    syn: [
      'Tortilla',
      'Tortillas',
      'Weizentortillas',
      'Weizentortilla',
      'Tortilla-Wraps',
      'Tortilla Wraps',
      'Weizen-Wraps',
      'Wrap-Fladen',
    ],
    aisle: 'brot',
    bls: 'B783012',
    g: { stueck: 60 },
    sell: { unit: 'packung', pieces: 6 },
  },
  {
    id: 'fladenbrot',
    name: 'Fladenbrot',
    plural: 'Fladenbrote',
    syn: ['türkisches Fladenbrot', 'Pide'],
    aisle: 'brot',
    bls: 'B782100',
    g: { stueck: 400 },
    sell: 'piece',
  },
  {
    id: 'pita',
    name: 'Pita',
    plural: 'Pitas',
    syn: ['Pitabrot', 'Pita-Brot', 'Pitataschen'],
    aisle: 'brot',
    bls: 'B782100',
    g: { stueck: 80 },
    sell: { unit: 'packung', pieces: 6 },
  },
  {
    id: 'laugenbrezel',
    name: 'Laugenbrezel',
    plural: 'Laugenbrezeln',
    syn: ['Brezel', 'Brezeln', 'Breze', 'Laugengebäck'],
    aisle: 'brot',
    bls: 'B723000',
    g: { stueck: 80 },
    sell: 'piece',
  },
  {
    id: 'knaeckebrot',
    name: 'Knäckebrot',
    aisle: 'brot',
    bls: 'B6A2100',
    g: { scheibe: 10, stueck: 10 },
    sell: { unit: 'packung', g: 250 },
  },

  // Milch & Kühlregal
  {
    id: 'ei',
    name: 'Ei',
    plural: 'Eier',
    syn: ['Hühnerei', 'Hühnereier', 'Eier Größe M', 'Eier Größe L'],
    aisle: 'kuehlregal',
    bls: 'E111100',
    g: { stueck: 55 },
    sell: { unit: 'packung', pieces: 10 },
  },
  {
    id: 'milch',
    name: 'Milch',
    syn: [
      'Vollmilch',
      'frische Milch',
      'H-Milch',
      'fettarme Milch',
      'Kuhmilch',
    ],
    aisle: 'kuehlregal',
    bls: 'M111300',
    density: 1.03,
    g: { tasse: 206 },
    sell: { unit: 'packung', ml: 1000 },
  },
  {
    id: 'haferdrink',
    name: 'Haferdrink',
    syn: ['Hafermilch', 'Haferdrink ungesüßt', 'Hafer-Drink'],
    aisle: 'kuehlregal',
    bls: 'C660000',
    density: 1.02,
    sell: { unit: 'packung', ml: 1000 },
  },
  {
    id: 'sojadrink',
    name: 'Sojadrink',
    syn: ['Sojamilch', 'Soja-Drink'],
    aisle: 'kuehlregal',
    bls: 'H841100',
    density: 1.02,
    sell: { unit: 'packung', ml: 1000 },
  },
  {
    id: 'mandeldrink',
    name: 'Mandeldrink',
    syn: ['Mandelmilch', 'Mandel-Drink'],
    aisle: 'kuehlregal',
    bls: 'H800000',
    density: 1.02,
    sell: { unit: 'packung', ml: 1000 },
  },
  {
    id: 'sahne',
    name: 'Sahne',
    syn: ['Schlagsahne', 'Kochsahne', 'süße Sahne', 'Rahm', 'Schlagrahm'],
    aisle: 'kuehlregal',
    bls: 'M173800',
    density: 1.0,
    g: { becher: 200 },
    sell: { unit: 'becher', ml: 200 },
  },
  {
    id: 'hafer-cuisine',
    name: 'Hafer-Cuisine',
    syn: [
      'Hafercuisine',
      'Hafer Cuisine',
      'Haferkochcreme',
      'Hafer-Kochcreme',
      'Haferkochsahne',
    ],
    aisle: 'kuehlregal',
    bls: 'M117700',
    density: 1.0,
    sell: { unit: 'packung', ml: 200 },
  },
  {
    id: 'soja-cuisine',
    name: 'Soja-Cuisine',
    syn: [
      'Sojacuisine',
      'Soja Cuisine',
      'Sojakochcreme',
      'Soja-Kochcreme',
      'Sojasahne',
    ],
    aisle: 'kuehlregal',
    bls: 'H845000',
    density: 1.0,
    sell: { unit: 'packung', ml: 200 },
  },
  {
    id: 'saure-sahne',
    name: 'Saure Sahne',
    syn: ['Sauerrahm'],
    aisle: 'kuehlregal',
    bls: 'M172500',
    g: { el: 15, becher: 200 },
    sell: { unit: 'becher', g: 200 },
  },
  {
    id: 'schmand',
    name: 'Schmand',
    aisle: 'kuehlregal',
    bls: 'M172700',
    g: { el: 15, becher: 200 },
    sell: { unit: 'becher', g: 200 },
  },
  {
    id: 'creme-fraiche',
    name: 'Crème fraîche',
    syn: ['Creme fraiche', 'Crème fraiche', 'Creme fraîche', 'Creme Fraiche'],
    aisle: 'kuehlregal',
    bls: 'M176800',
    g: { el: 15, becher: 150 },
    sell: { unit: 'becher', g: 150 },
  },
  {
    id: 'butter',
    name: 'Butter',
    syn: ['Süßrahmbutter', 'Sauerrahmbutter', 'mildgesäuerte Butter'],
    aisle: 'kuehlregal',
    bls: 'Q611000',
    g: { el: 14, tl: 5, stueck: 10 },
    sell: { unit: 'packung', g: 250 },
  },
  {
    id: 'margarine',
    name: 'Margarine',
    syn: ['Pflanzenmargarine', 'vegane Butter'],
    aisle: 'kuehlregal',
    bls: 'Q400000',
    g: { el: 14, tl: 5 },
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'joghurt',
    name: 'Joghurt',
    syn: ['Naturjoghurt', 'Joghurt natur', 'Vollmilchjoghurt', 'Jogurt'],
    aisle: 'kuehlregal',
    bls: 'M141300',
    g: { el: 15, becher: 500 },
    sell: { unit: 'becher', g: 500 },
  },
  {
    id: 'griechischer-joghurt',
    name: 'Griechischer Joghurt',
    syn: ['Joghurt griechischer Art', 'griechischer Sahnejoghurt'],
    aisle: 'kuehlregal',
    bls: 'M141500',
    g: { el: 15 },
    sell: { unit: 'becher', g: 500 },
  },
  {
    id: 'skyr',
    name: 'Skyr',
    aisle: 'kuehlregal',
    bls: 'M710100',
    g: { el: 15 },
    sell: { unit: 'becher', g: 450 },
  },
  {
    id: 'quark',
    name: 'Quark',
    syn: ['Magerquark', 'Speisequark', 'Quark mager', 'Quark Magerstufe'],
    aisle: 'kuehlregal',
    bls: 'M713100',
    g: { el: 20, becher: 250 },
    sell: { unit: 'becher', g: 250 },
  },
  {
    id: 'frischkaese',
    name: 'Frischkäse',
    syn: [
      'Doppelrahmfrischkäse',
      'Frischkäse natur',
      'Frischkäse Doppelrahmstufe',
      'Rahmfrischkäse',
    ],
    aisle: 'kuehlregal',
    bls: 'M710800',
    g: { el: 20, tl: 7 },
    sell: { unit: 'packung', g: 200 },
  },
  {
    id: 'mascarpone',
    name: 'Mascarpone',
    aisle: 'kuehlregal',
    bls: 'M7A6800',
    g: { el: 20 },
    sell: { unit: 'packung', g: 250 },
  },
  {
    id: 'ricotta',
    name: 'Ricotta',
    aisle: 'kuehlregal',
    bls: 'M741600',
    g: { el: 20 },
    sell: { unit: 'packung', g: 250 },
  },
  {
    id: 'mozzarella',
    name: 'Mozzarella',
    syn: [
      'Mozzarellakugel',
      'Mozzarella-Kugel',
      'Büffelmozzarella',
      'Mini-Mozzarella',
      'Mozzarella am Stück',
    ],
    aisle: 'kuehlregal',
    bls: 'M032100',
    g: { stueck: 125 },
    sell: { unit: 'packung', g: 125 },
  },
  {
    id: 'mozzarella-gerieben',
    name: 'Geriebener Mozzarella',
    syn: [
      'Mozzarella gerieben',
      'Pizza-Mozzarella',
      'Pizzakäse',
      'geriebenen Mozzarella',
    ],
    aisle: 'kuehlregal',
    bls: 'M032100',
    g: { handvoll: 30, el: 8 },
    sell: { unit: 'beutel', g: 200 },
  },
  {
    id: 'feta',
    name: 'Feta',
    syn: [
      'Schafskäse',
      'Hirtenkäse',
      'Fetakäse',
      'Feta-Käse',
      'Salatkäse',
      'Feta am Stück',
    ],
    aisle: 'kuehlregal',
    bls: 'M012200',
    g: { stueck: 200 },
    sell: { unit: 'packung', g: 200 },
  },
  {
    id: 'halloumi',
    name: 'Halloumi',
    syn: ['Grillkäse', 'Halloumi-Käse'],
    aisle: 'kuehlregal',
    bls: 'M524500',
    g: { scheibe: 30 },
    sell: { unit: 'packung', g: 225 },
  },
  {
    id: 'parmesan',
    name: 'Parmesan',
    syn: [
      'Parmigiano',
      'Parmigiano Reggiano',
      'Grana Padano',
      'Hartkäse',
      'geriebener Parmesan',
      'Parmesan gerieben',
    ],
    aisle: 'kuehlregal',
    bls: 'M306400',
    g: { el: 5, tl: 2, handvoll: 25 },
    sell: { unit: 'packung', g: 100 },
  },
  {
    id: 'gouda',
    name: 'Gouda',
    syn: ['junger Gouda', 'mittelalter Gouda', 'alter Gouda', 'Goudakäse'],
    aisle: 'kuehlregal',
    bls: 'M402600',
    g: { scheibe: 20 },
    sell: { unit: 'stueck', g: 400 },
  },
  {
    id: 'emmentaler',
    name: 'Emmentaler',
    syn: ['Bergkäse', 'Emmentaler am Stück'],
    aisle: 'kuehlregal',
    bls: 'M304600',
    g: { scheibe: 20 },
    sell: { unit: 'packung', g: 250 },
  },
  {
    id: 'edamer',
    name: 'Edamer',
    aisle: 'kuehlregal',
    bls: 'M401600',
    g: { scheibe: 20 },
    sell: { unit: 'packung', g: 250 },
  },
  {
    id: 'kaese-gerieben',
    name: 'Geriebener Käse',
    syn: [
      'Käse gerieben',
      'Reibekäse',
      'Gratinkäse',
      'Emmentaler gerieben',
      'Gouda gerieben',
      'Streukäse',
      'Käse zum Überbacken',
      'Reibekäse Gouda',
    ],
    aisle: 'kuehlregal',
    bls: 'M402600',
    g: { handvoll: 30, el: 8 },
    sell: { unit: 'beutel', g: 200 },
  },
  {
    id: 'kaesescheiben',
    name: 'Käsescheibe',
    plural: 'Käsescheiben',
    syn: [
      'Käse in Scheiben',
      'Scheibenkäse',
      'Goudascheiben',
      'Toastkäse',
      'Sandwichkäse',
    ],
    aisle: 'kuehlregal',
    bls: 'M402600',
    g: { scheibe: 20, stueck: 20 },
    sell: { unit: 'packung', pieces: 8 },
  },
  {
    id: 'pizzateig',
    name: 'Pizzateig',
    syn: [
      'frischer Pizzateig',
      'Pizzateig aus dem Kühlregal',
      'Pizzateig-Rolle',
      'Hefeteig für Pizza',
    ],
    aisle: 'kuehlregal',
    bls: 'D079000',
    g: { stueck: 400, rolle: 400, packung: 400 },
    sell: { unit: 'rolle', g: 400 },
  },
  {
    id: 'blaetterteig',
    name: 'Blätterteig',
    syn: ['Blätterteig-Rolle', 'frischer Blätterteig'],
    aisle: 'kuehlregal',
    bls: 'D072000',
    g: { rolle: 275, packung: 275 },
    sell: { unit: 'rolle', g: 275 },
  },
  {
    id: 'gnocchi',
    name: 'Gnocchi',
    syn: ['Kartoffelgnocchi', 'frische Gnocchi'],
    aisle: 'kuehlregal',
    bls: 'K270000',
    sell: { unit: 'packung', g: 500 },
  },

  // Tofu & Veggie
  {
    id: 'tofu',
    name: 'Tofu',
    syn: ['Tofu natur', 'Naturtofu', 'fester Tofu'],
    aisle: 'veggie',
    bls: 'H861000',
    sell: { unit: 'packung', g: 200 },
  },
  {
    id: 'raeuchertofu',
    name: 'Räuchertofu',
    syn: ['geräucherter Tofu', 'Tofu geräuchert', 'Räucher-Tofu'],
    aisle: 'veggie',
    bls: 'H861000',
    sell: { unit: 'packung', g: 200 },
  },
  {
    id: 'seidentofu',
    name: 'Seidentofu',
    aisle: 'veggie',
    bls: 'H861100',
    sell: { unit: 'packung', g: 400 },
  },
  {
    id: 'seitan',
    name: 'Seitan',
    aisle: 'veggie',
    bls: 'C558000',
    sell: { unit: 'packung', g: 200 },
  },

  // Fleisch & Fisch
  {
    id: 'haehnchenbrust',
    name: 'Hähnchenbrust',
    syn: [
      'Hähnchenbrustfilet',
      'Hähnchenbrustfilets',
      'Hühnerbrust',
      'Hähnchenfilet',
      'Hühnchenbrust',
      'Hühnerbrustfilet',
    ],
    aisle: 'fleisch-fisch',
    bls: 'V416100',
    g: { stueck: 180 },
    sell: { unit: 'packung', g: 400 },
  },
  {
    id: 'hackfleisch',
    name: 'Hackfleisch',
    syn: [
      'Hack',
      'gemischtes Hackfleisch',
      'Hackfleisch gemischt',
      'Gehacktes',
    ],
    aisle: 'fleisch-fisch',
    bls: 'U020100',
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'rinderhack',
    name: 'Rinderhack',
    syn: ['Rinderhackfleisch', 'Hackfleisch vom Rind'],
    aisle: 'fleisch-fisch',
    bls: 'U010100',
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'speck',
    name: 'Speckwürfel',
    syn: [
      'Speck',
      'Schinkenwürfel',
      'Bacon',
      'Frühstücksspeck',
      'Bauchspeck',
      'Baconwürfel',
    ],
    aisle: 'fleisch-fisch',
    bls: 'U642100',
    g: { scheibe: 10 },
    sell: { unit: 'packung', g: 125 },
  },
  {
    id: 'kochschinken',
    name: 'Kochschinken',
    syn: [
      'gekochter Schinken',
      'Schinken',
      'Schinkenscheiben',
      'Kochschinkenscheiben',
    ],
    aisle: 'fleisch-fisch',
    bls: 'W424000',
    g: { scheibe: 20 },
    sell: { unit: 'packung', g: 100 },
  },
  {
    id: 'salami',
    name: 'Salami',
    syn: ['Salamischeiben', 'Pizzasalami'],
    aisle: 'fleisch-fisch',
    bls: 'W140000',
    g: { scheibe: 8 },
    sell: { unit: 'packung', g: 100 },
  },
  {
    id: 'wiener',
    name: 'Wiener Würstchen',
    syn: ['Wiener', 'Würstchen', 'Wienerle', 'Frankfurter Würstchen'],
    aisle: 'fleisch-fisch',
    bls: 'W211200',
    g: { stueck: 50 },
    sell: { unit: 'packung', pieces: 6 },
  },
  {
    id: 'lachs',
    name: 'Lachsfilet',
    plural: 'Lachsfilets',
    syn: ['Lachs', 'Lachsfilets ohne Haut', 'Lachsfilet mit Haut'],
    aisle: 'fleisch-fisch',
    bls: 'T410100',
    g: { stueck: 125 },
    sell: { unit: 'packung', g: 250 },
  },
  {
    id: 'garnelen',
    name: 'Garnelen',
    syn: [
      'Shrimps',
      'Crevetten',
      'Riesengarnelen',
      'Garnelen TK',
      'King Prawns',
    ],
    aisle: 'tiefkuehl',
    bls: 'T753200',
    g: { stueck: 15 },
    sell: { unit: 'packung', g: 250 },
  },

  // Nudeln, Reis & Getreide
  {
    id: 'spaghetti',
    name: 'Spaghetti',
    syn: ['Spaghettini', 'Linguine'],
    aisle: 'trocken',
    bls: 'E401000',
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'nudeln',
    name: 'Nudeln',
    syn: [
      'Pasta',
      'Teigwaren',
      'Fusilli',
      'Spirelli',
      'Locken',
      'Farfalle',
      'Rigatoni',
      'Makkaroni',
      'Hörnchennudeln',
      'Muschelnudeln',
      'Tagliatelle',
      'Bandnudeln',
      'kurze Nudeln',
      'Nudeln nach Wahl',
    ],
    aisle: 'trocken',
    bls: 'E401000',
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'penne',
    name: 'Penne',
    syn: ['Penne Rigate'],
    aisle: 'trocken',
    bls: 'E401000',
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'vollkornnudeln',
    name: 'Vollkornnudeln',
    syn: ['Vollkornpasta', 'Vollkornspaghetti', 'Vollkorn-Nudeln'],
    aisle: 'trocken',
    bls: 'E510000',
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'lasagneplatten',
    name: 'Lasagneplatten',
    syn: [
      'Lasagnenudeln',
      'Lasagneblätter',
      'Lasagne-Platten',
      'Lasagneplatte',
    ],
    aisle: 'trocken',
    bls: 'E401000',
    g: { stueck: 20, blatt: 20 },
    sell: { unit: 'packung', g: 250 },
  },
  {
    id: 'cannelloni',
    name: 'Cannelloni',
    syn: ['Cannelloni-Röhren', 'Cannellonirohre'],
    aisle: 'trocken',
    bls: 'E401000',
    g: { stueck: 8 },
    sell: { unit: 'packung', g: 250 },
  },
  {
    id: 'reisnudeln',
    name: 'Reisnudeln',
    syn: ['Reisbandnudeln', 'Reis-Nudeln'],
    aisle: 'trocken',
    bls: 'C559000',
    sell: { unit: 'packung', g: 250 },
  },
  {
    id: 'reispapier',
    name: 'Reispapier',
    syn: [
      'Reispapierblätter',
      'Reispapierblatt',
      'Reisblätter',
      'Reispapier-Blätter',
      'Frühlingsrollenblätter',
    ],
    aisle: 'trocken',
    bls: 'C559000',
    g: { blatt: 9, stueck: 9 },
    sell: { unit: 'packung', g: 200 },
  },
  {
    id: 'reis',
    name: 'Reis',
    syn: [
      'Langkornreis',
      'weißer Reis',
      'Parboiled Reis',
      'Kochbeutelreis',
      'Reis nach Wahl',
    ],
    aisle: 'trocken',
    bls: 'C352000',
    g: { tasse: 185 },
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'basmatireis',
    name: 'Basmatireis',
    syn: ['Basmati', 'Basmati-Reis'],
    aisle: 'trocken',
    bls: 'C352000',
    g: { tasse: 185 },
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'jasminreis',
    name: 'Jasminreis',
    syn: ['Jasmin-Reis', 'Duftreis'],
    aisle: 'trocken',
    bls: 'C352000',
    g: { tasse: 185 },
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'naturreis',
    name: 'Naturreis',
    syn: ['Vollkornreis', 'brauner Reis'],
    aisle: 'trocken',
    bls: 'C351000',
    g: { tasse: 185 },
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'risottoreis',
    name: 'Risottoreis',
    syn: ['Arborio', 'Arborio-Reis', 'Carnaroli', 'Risotto-Reis'],
    aisle: 'trocken',
    bls: 'C352000',
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'milchreis',
    name: 'Milchreis',
    syn: ['Rundkornreis'],
    aisle: 'trocken',
    bls: 'C352000',
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'couscous',
    name: 'Couscous',
    syn: ['Cous Cous', 'Kuskus'],
    aisle: 'trocken',
    bls: 'C119200',
    g: { tasse: 170, glas: 170 },
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'bulgur',
    name: 'Bulgur',
    aisle: 'trocken',
    bls: 'C119100',
    g: { tasse: 170 },
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'quinoa',
    name: 'Quinoa',
    aisle: 'trocken',
    bls: 'C118000',
    g: { tasse: 170 },
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'polenta',
    name: 'Polenta',
    syn: ['Maisgrieß'],
    aisle: 'trocken',
    bls: 'C443000',
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'rote-linsen',
    name: 'Rote Linsen',
    syn: ['Linsen rot', 'rote Linse', 'Rote Linse'],
    aisle: 'trocken',
    bls: 'H730000',
    g: { tasse: 190 },
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'linsen',
    name: 'Linsen',
    syn: [
      'braune Linsen',
      'Tellerlinsen',
      'Belugalinsen',
      'Berglinsen',
      'Linse',
      'grüne Linsen',
    ],
    aisle: 'trocken',
    bls: 'H725100',
    g: { tasse: 190 },
    sell: { unit: 'packung', g: 500 },
  },

  // Konserven & Gläser
  {
    id: 'gehackte-tomaten',
    name: 'Gehackte Tomaten',
    syn: [
      'Dose Tomaten',
      'Tomaten in der Dose',
      'stückige Tomaten',
      'Tomaten gehackt',
      'Tomatenstücke',
      'Dosentomaten',
      'geschälte Tomaten',
      'Pizzatomaten',
      'Tomaten aus der Dose',
      'Tomaten in Stücken',
    ],
    aisle: 'konserven',
    bls: 'G568900',
    g: { dose: 400 },
    sell: { unit: 'dose', g: 400 },
  },
  {
    id: 'passierte-tomaten',
    name: 'Passierte Tomaten',
    syn: ['Passata', 'Tomatenpassata', 'Tomatenpüree', 'Tomaten passiert'],
    aisle: 'konserven',
    bls: 'R161200',
    density: 1.05,
    g: { packung: 500 },
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'tomatenmark',
    name: 'Tomatenmark',
    syn: ['Tomatenkonzentrat'],
    aisle: 'konserven',
    bls: 'R160000',
    g: { el: 16, tl: 5 },
    sell: { unit: 'tube', g: 200 },
  },
  {
    id: 'tomatensauce',
    name: 'Tomatensauce',
    syn: [
      'Pizzasauce',
      'Tomatensoße',
      'Pastasauce',
      'Pizza-Sauce',
      'Tomatensugo',
      'Sugo',
    ],
    aisle: 'konserven',
    bls: 'R161200',
    density: 1.05,
    g: { el: 16 },
    sell: { unit: 'glas', g: 400 },
  },
  {
    id: 'kokosmilch',
    name: 'Kokosmilch',
    syn: ['Kokosnussmilch', 'Kokosmilch light', 'Kokoscreme'],
    aisle: 'konserven',
    bls: 'H154000',
    density: 1.0,
    g: { dose: 400 },
    sell: { unit: 'dose', ml: 400 },
  },
  {
    id: 'kidneybohnen',
    name: 'Kidneybohnen',
    syn: ['rote Bohnen', 'Kidney-Bohnen', 'Kidneybohne'],
    aisle: 'konserven',
    bls: 'H742902',
    g: { dose: 250 },
    sell: { unit: 'dose', g: 250 },
  },
  {
    id: 'kichererbsen',
    name: 'Kichererbsen',
    syn: ['Kichererbse', 'Kichererbsen aus der Dose'],
    aisle: 'konserven',
    bls: 'H720902',
    g: { dose: 240, el: 15 },
    sell: { unit: 'dose', g: 240 },
  },
  {
    id: 'weisse-bohnen',
    name: 'Weiße Bohnen',
    syn: ['Cannellini-Bohnen', 'Cannellini Bohnen', 'weiße Riesenbohnen'],
    aisle: 'konserven',
    bls: 'H740902',
    g: { dose: 250 },
    sell: { unit: 'dose', g: 250 },
  },
  {
    id: 'mais',
    name: 'Mais',
    syn: ['Dosenmais', 'Zuckermais', 'Gemüsemais', 'Maiskörner'],
    aisle: 'konserven',
    bls: 'G570902',
    g: { dose: 285, el: 15 },
    sell: { unit: 'dose', g: 285 },
  },
  {
    id: 'ananas-stuecke',
    name: 'Ananas in Stücken',
    syn: [
      'Ananasstücke',
      'Ananas-Stücke',
      'Ananas aus der Dose',
      'Ananas Dose',
    ],
    aisle: 'konserven',
    bls: 'F5A1902',
    g: { dose: 340, el: 15 },
    sell: { unit: 'dose', g: 340 },
  },
  {
    id: 'ananasscheiben',
    name: 'Ananasscheibe',
    plural: 'Ananasscheiben',
    syn: ['Ananasringe', 'Ananas in Scheiben'],
    aisle: 'konserven',
    bls: 'F5A1902',
    g: { scheibe: 40, stueck: 40 },
    sell: { unit: 'dose', g: 340 },
  },
  {
    id: 'getrocknete-tomaten',
    name: 'Getrocknete Tomaten',
    syn: [
      'Tomaten getrocknet',
      'sonnengetrocknete Tomaten',
      'getrocknete Tomaten in Öl',
      'Softtomaten',
    ],
    aisle: 'konserven',
    bls: 'G567702',
    g: { stueck: 6, el: 10 },
    sell: { unit: 'glas', g: 150 },
  },
  {
    id: 'oliven',
    name: 'Oliven',
    syn: [
      'schwarze Oliven',
      'grüne Oliven',
      'Oliven entsteint',
      'Kalamata-Oliven',
    ],
    aisle: 'konserven',
    bls: 'H520800',
    g: { stueck: 4, el: 12, handvoll: 40 },
    sell: { unit: 'glas', g: 160 },
  },
  {
    id: 'kapern',
    name: 'Kapern',
    aisle: 'konserven',
    bls: 'G012902',
    g: { el: 8, tl: 3 },
    sell: { unit: 'glas', g: 50 },
  },
  {
    id: 'pesto',
    name: 'Pesto',
    syn: [
      'grünes Pesto',
      'Pesto verde',
      'Pesto Genovese',
      'Basilikumpesto',
      'Pesto alla Genovese',
    ],
    aisle: 'konserven',
    bls: 'X372012',
    g: { el: 15, tl: 5 },
    sell: { unit: 'glas', g: 190 },
  },
  {
    id: 'pesto-rosso',
    name: 'Pesto rosso',
    syn: ['rotes Pesto', 'Tomatenpesto'],
    aisle: 'konserven',
    bls: 'X3A7010',
    g: { el: 15, tl: 5 },
    sell: { unit: 'glas', g: 190 },
  },
  {
    id: 'spargel-glas',
    name: 'Spargel aus dem Glas',
    syn: [
      'weißer Spargel aus dem Glas',
      'Spargel im Glas',
      'Spargelstangen aus dem Glas',
      'Spargelabschnitte',
    ],
    aisle: 'konserven',
    bls: 'G450132',
    g: { glas: 205, stange: 20 },
    sell: { unit: 'glas', g: 205 },
  },
  {
    id: 'thunfisch',
    name: 'Thunfisch',
    syn: [
      'Thunfisch in der Dose',
      'Thunfisch im eigenen Saft',
      'Thunfisch naturell',
      'Thunfischdose',
    ],
    aisle: 'konserven',
    bls: 'T121902',
    g: { dose: 150 },
    sell: { unit: 'dose', g: 150 },
  },

  // Backzutaten
  {
    id: 'mehl',
    name: 'Mehl',
    syn: [
      'Weizenmehl',
      'Weizenmehl Type 405',
      'Mehl Type 405',
      'Type 405',
      'Dinkelmehl',
      'Weizenmehl 405',
    ],
    aisle: 'backen',
    bls: 'C214100',
    g: { el: 10, tl: 3, tasse: 120 },
    sell: { unit: 'packung', g: 1000 },
    pantry: 'often',
  },
  {
    id: 'zucker',
    name: 'Zucker',
    syn: [
      'weißer Zucker',
      'Haushaltszucker',
      'Kristallzucker',
      'feiner Zucker',
    ],
    aisle: 'backen',
    bls: 'S111000',
    g: { el: 15, tl: 5, prise: 0.5 },
    sell: { unit: 'packung', g: 1000 },
    pantry: 'often',
  },
  {
    id: 'brauner-zucker',
    name: 'Brauner Zucker',
    syn: ['Rohrzucker', 'Rohrohrzucker'],
    aisle: 'backen',
    bls: 'S111000',
    g: { el: 15, tl: 5 },
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'puderzucker',
    name: 'Puderzucker',
    aisle: 'backen',
    bls: 'S111000',
    g: { el: 8, tl: 3 },
    sell: { unit: 'packung', g: 250 },
  },
  {
    id: 'vanillezucker',
    name: 'Vanillezucker',
    syn: ['Bourbon-Vanillezucker'],
    aisle: 'backen',
    bls: 'S114000',
    g: { packung: 8, tl: 4 },
    sell: { unit: 'packung', g: 8 },
  },
  {
    id: 'backpulver',
    name: 'Backpulver',
    aisle: 'backen',
    nutrition: false,
    g: { packung: 15, tl: 4 },
    sell: { unit: 'packung', g: 15 },
  },
  {
    id: 'trockenhefe',
    name: 'Trockenhefe',
    syn: ['Backhefe getrocknet', 'Trockenbackhefe'],
    aisle: 'backen',
    nutrition: false,
    g: { packung: 7 },
    sell: { unit: 'packung', g: 7 },
  },
  {
    id: 'frischhefe',
    name: 'Frische Hefe',
    syn: ['Frischhefe', 'Hefewürfel', 'Würfel Hefe'],
    aisle: 'kuehlregal',
    nutrition: false,
    g: { wuerfel: 42, packung: 42 },
    sell: { unit: 'wuerfel', g: 42 },
  },
  {
    id: 'speisestaerke',
    name: 'Speisestärke',
    syn: ['Stärke', 'Maisstärke', 'Kartoffelstärke'],
    aisle: 'backen',
    bls: 'C446000',
    g: { el: 10, tl: 3 },
    sell: { unit: 'packung', g: 400 },
  },
  {
    id: 'paniermehl',
    name: 'Paniermehl',
    syn: ['Semmelbrösel', 'Semmelmehl', 'Panko'],
    aisle: 'backen',
    bls: 'B821000',
    g: { el: 8 },
    sell: { unit: 'packung', g: 400 },
  },
  {
    id: 'kakao',
    name: 'Kakaopulver',
    syn: ['Kakao', 'Backkakao'],
    aisle: 'backen',
    bls: 'S711000',
    g: { el: 6, tl: 2 },
    sell: { unit: 'packung', g: 250 },
  },

  // Öl, Essig, Gewürze & Saucen
  {
    id: 'oel',
    name: 'Öl',
    syn: [
      'Speiseöl',
      'Rapsöl',
      'Sonnenblumenöl',
      'Pflanzenöl',
      'Bratöl',
      'neutrales Öl',
      'Fett',
      'Öl zum Braten',
    ],
    aisle: 'wuerzen',
    bls: 'Q180000',
    density: 0.92,
    g: { el: 13, tl: 4.5, spritzer: 2, schuss: 10 },
    sell: { unit: 'flasche', ml: 1000 },
    pantry: 'often',
  },
  {
    id: 'olivenoel',
    name: 'Olivenöl',
    syn: ['natives Olivenöl', 'Olivenöl extra vergine', 'Olivenöl nativ extra'],
    aisle: 'wuerzen',
    bls: 'Q120000',
    density: 0.92,
    g: { el: 13, tl: 4.5, spritzer: 2, schuss: 10 },
    sell: { unit: 'flasche', ml: 500 },
    pantry: 'often',
  },
  {
    id: 'leinoel',
    name: 'Leinöl',
    aisle: 'wuerzen',
    bls: 'Q160000',
    density: 0.93,
    g: { el: 13, tl: 4.5 },
    sell: { unit: 'flasche', ml: 250 },
  },
  {
    id: 'sesamoel',
    name: 'Sesamöl',
    syn: ['geröstetes Sesamöl'],
    aisle: 'wuerzen',
    bls: 'Q230000',
    density: 0.92,
    g: { el: 13, tl: 4.5 },
    sell: { unit: 'flasche', ml: 250 },
  },
  {
    id: 'essig',
    name: 'Essig',
    syn: [
      'Weinessig',
      'Weißweinessig',
      'Rotweinessig',
      'Kräuteressig',
      'Apfelessig',
      'Branntweinessig',
      'Obstessig',
    ],
    aisle: 'wuerzen',
    bls: 'R121000',
    density: 1.0,
    g: { spritzer: 2, schuss: 10 },
    sell: { unit: 'flasche', ml: 500 },
  },
  {
    id: 'balsamico',
    name: 'Balsamico',
    syn: [
      'Balsamessig',
      'Aceto Balsamico',
      'heller Balsamico',
      'Balsamico bianco',
      'dunkler Balsamico',
      'Balsamicoessig',
      'weißer Balsamico',
    ],
    aisle: 'wuerzen',
    bls: 'R125000',
    density: 1.06,
    g: { spritzer: 2, schuss: 10 },
    sell: { unit: 'flasche', ml: 500 },
  },
  {
    id: 'salz',
    name: 'Salz',
    syn: [
      'Speisesalz',
      'Meersalz',
      'Jodsalz',
      'Steinsalz',
      'Salzflocken',
      'grobes Salz',
    ],
    aisle: 'wuerzen',
    nutrition: false,
    g: { tl: 6, prise: 0.5 },
    sell: { unit: 'packung', g: 500 },
    pantry: 'often',
  },
  {
    id: 'pfeffer',
    name: 'Pfeffer',
    syn: [
      'schwarzer Pfeffer',
      'Pfeffer aus der Mühle',
      'Pfeffer schwarz',
      'weißer Pfeffer',
      'frisch gemahlener Pfeffer',
    ],
    aisle: 'wuerzen',
    nutrition: false,
    sell: { unit: 'packung', g: 50 },
    pantry: 'often',
  },
  {
    id: 'gewuerze',
    name: 'Gewürze',
    syn: [
      'weitere Gewürze',
      'Gewürzmischung',
      'Lieblingsgewürze',
      'Gewürze nach Wahl',
      'Gewürz',
    ],
    aisle: 'wuerzen',
    nutrition: false,
    pantry: 'often',
  },
  {
    id: 'paprikapulver',
    name: 'Paprikapulver',
    syn: [
      'Paprika edelsüß',
      'Paprika rosenscharf',
      'geräuchertes Paprikapulver',
      'Paprika edelsuess',
      'Paprikagewürz',
    ],
    aisle: 'wuerzen',
    nutrition: false,
    sell: { unit: 'packung', g: 50 },
  },
  {
    id: 'currypulver',
    name: 'Currypulver',
    syn: ['Curry', 'Curry-Pulver', 'Currygewürz'],
    aisle: 'wuerzen',
    nutrition: false,
    sell: { unit: 'packung', g: 50 },
  },
  {
    id: 'kreuzkuemmel',
    name: 'Kreuzkümmel',
    syn: ['Cumin', 'Kreuzkümmel gemahlen'],
    aisle: 'wuerzen',
    nutrition: false,
    sell: { unit: 'packung', g: 40 },
  },
  {
    id: 'kuemmel',
    name: 'Kümmel',
    syn: ['Kümmelsamen', 'gemahlener Kümmel'],
    aisle: 'wuerzen',
    nutrition: false,
    sell: { unit: 'packung', g: 40 },
  },
  {
    id: 'kurkuma',
    name: 'Kurkuma',
    syn: ['Kurkumapulver', 'Gelbwurz', 'Kurkuma gemahlen'],
    aisle: 'wuerzen',
    nutrition: false,
    sell: { unit: 'packung', g: 40 },
  },
  {
    id: 'zimt',
    name: 'Zimt',
    syn: ['Zimtpulver', 'Zimtstange', 'Zimt gemahlen'],
    aisle: 'wuerzen',
    nutrition: false,
    sell: { unit: 'packung', g: 40 },
  },
  {
    id: 'muskat',
    name: 'Muskat',
    syn: ['Muskatnuss', 'Muskatnuss gerieben', 'Muskat gerieben'],
    aisle: 'wuerzen',
    nutrition: false,
    sell: { unit: 'packung', g: 20 },
  },
  {
    id: 'oregano',
    name: 'Oregano',
    syn: ['getrockneter Oregano'],
    aisle: 'wuerzen',
    nutrition: false,
    sell: { unit: 'packung', g: 15 },
  },
  {
    id: 'italienische-kraeuter',
    name: 'Italienische Kräuter',
    syn: [
      'getrocknete italienische Kräuter',
      'Kräuter der Provence',
      'italienische Kräutermischung',
      'getrocknete Kräuter',
      'Pizzagewürz',
    ],
    aisle: 'wuerzen',
    nutrition: false,
    sell: { unit: 'packung', g: 20 },
  },
  {
    id: 'chiliflocken',
    name: 'Chiliflocken',
    syn: [
      'Chili-Flocken',
      'Chilipulver',
      'Cayennepfeffer',
      'Chili getrocknet',
      'Pul Biber',
    ],
    aisle: 'wuerzen',
    nutrition: false,
    sell: { unit: 'packung', g: 40 },
  },
  {
    id: 'gemuesebruehe',
    name: 'Gemüsebrühe',
    syn: [
      'Brühe',
      'Gemüsebrühepulver',
      'Gemüsebouillon',
      'Instantbrühe',
      'Brühwürfel',
      'Gemüsebrühe Pulver',
      'Gemüsefond',
      'Gemüsebrühwürfel',
      'heiße Brühe',
      'Bouillon',
    ],
    aisle: 'wuerzen',
    nutrition: false,
    density: 0.02,
    g: { tl: 5, el: 12, wuerfel: 10 },
    sell: { unit: 'glas', g: 150 },
  },
  {
    id: 'sojasauce',
    name: 'Sojasauce',
    syn: [
      'Sojasoße',
      'Shoyu',
      'Soja-Sauce',
      'helle Sojasauce',
      'dunkle Sojasauce',
    ],
    aisle: 'wuerzen',
    bls: 'R143000',
    density: 1.1,
    g: { spritzer: 2, schuss: 10 },
    sell: { unit: 'flasche', ml: 250 },
  },
  {
    id: 'currypaste',
    name: 'Currypaste',
    syn: [
      'rote Currypaste',
      'grüne Currypaste',
      'gelbe Currypaste',
      'Thai-Currypaste',
      'Curry-Paste',
    ],
    aisle: 'wuerzen',
    nutrition: false,
    g: { el: 15, tl: 5 },
    sell: { unit: 'glas', g: 110 },
  },
  {
    id: 'senf',
    name: 'Senf',
    syn: [
      'mittelscharfer Senf',
      'Dijonsenf',
      'Dijon-Senf',
      'süßer Senf',
      'scharfer Senf',
      'Körnersenf',
    ],
    aisle: 'wuerzen',
    bls: 'R132000',
    g: { tl: 5, el: 15 },
    sell: { unit: 'tube', g: 200 },
  },
  {
    id: 'ketchup',
    name: 'Ketchup',
    syn: ['Tomatenketchup'],
    aisle: 'wuerzen',
    bls: 'R141100',
    g: { el: 17, tl: 6 },
    sell: { unit: 'flasche', g: 500 },
  },
  {
    id: 'mayonnaise',
    name: 'Mayonnaise',
    syn: ['Mayo', 'Salatmayonnaise'],
    aisle: 'wuerzen',
    bls: 'Q991000',
    g: { el: 15, tl: 5 },
    sell: { unit: 'glas', g: 250 },
  },
  {
    id: 'burgersauce',
    name: 'Burgersauce',
    syn: ['Burger-Sauce', 'Burgersoße', 'Sandwichsauce', 'Grillsauce'],
    aisle: 'wuerzen',
    bls: 'X344060',
    g: { el: 15, tl: 5 },
    sell: { unit: 'flasche', g: 250 },
  },
  {
    id: 'salatdressing',
    name: 'Salatdressing',
    syn: [
      'Dressing',
      'Joghurtdressing',
      'Joghurt-Dressing',
      'Salatsauce',
      'Dressing nach Wahl',
      'Joghurt-Zitronen-Dressing',
    ],
    aisle: 'wuerzen',
    bls: 'X344060',
    density: 1.0,
    g: { el: 15, tl: 5 },
    sell: { unit: 'flasche', ml: 250 },
  },
  {
    id: 'dip',
    name: 'Dip',
    syn: ['Dip nach Wahl', 'Kräuterdip', 'Sour-Cream-Dip'],
    aisle: 'kuehlregal',
    bls: 'X3A9040',
    g: { el: 15 },
    sell: { unit: 'becher', g: 200 },
  },
  {
    id: 'zitronensaft',
    name: 'Zitronensaft',
    syn: ['Saft einer Zitrone'],
    aisle: 'wuerzen',
    bls: 'F601600',
    density: 1.03,
    g: { spritzer: 2, schuss: 10 },
    sell: { unit: 'flasche', ml: 200 },
  },

  // Frühstück, Nüsse & Süßes
  {
    id: 'haferflocken',
    name: 'Haferflocken',
    syn: [
      'zarte Haferflocken',
      'kernige Haferflocken',
      'Hafer Flocken',
      'Porridge-Haferflocken',
    ],
    aisle: 'fruehstueck',
    bls: 'C133000',
    g: { el: 10, tasse: 90 },
    sell: { unit: 'packung', g: 500 },
  },
  {
    id: 'muesli',
    name: 'Müsli',
    syn: ['Früchtemüsli', 'Knuspermüsli', 'Granola'],
    aisle: 'fruehstueck',
    bls: 'C538000',
    g: { el: 8, tasse: 100 },
    sell: { unit: 'packung', g: 750 },
  },
  {
    id: 'honig',
    name: 'Honig',
    aisle: 'fruehstueck',
    bls: 'S120000',
    density: 1.4,
    g: { el: 21, tl: 7 },
    sell: { unit: 'glas', g: 500 },
  },
  {
    id: 'ahornsirup',
    name: 'Ahornsirup',
    syn: ['Ahorn-Sirup'],
    aisle: 'fruehstueck',
    bls: 'S151100',
    density: 1.32,
    g: { el: 20, tl: 7 },
    sell: { unit: 'flasche', ml: 250 },
  },
  {
    id: 'marmelade',
    name: 'Marmelade',
    syn: ['Konfitüre', 'Fruchtaufstrich'],
    aisle: 'fruehstueck',
    bls: 'S132000',
    g: { el: 20, tl: 7 },
    sell: { unit: 'glas', g: 450 },
  },
  {
    id: 'nuss-nougat-creme',
    name: 'Nuss-Nougat-Creme',
    syn: ['Nutella', 'Schokoaufstrich', 'Nougatcreme'],
    aisle: 'fruehstueck',
    bls: 'S145000',
    g: { el: 20, tl: 7 },
    sell: { unit: 'glas', g: 400 },
  },
  {
    id: 'erdnussmus',
    name: 'Erdnussmus',
    syn: ['Erdnussbutter', 'Erdnusscreme', 'Erdnuss-Mus', 'Peanutbutter'],
    aisle: 'fruehstueck',
    bls: 'H110800',
    g: { el: 16, tl: 5 },
    sell: { unit: 'glas', g: 250 },
  },
  {
    id: 'walnuss',
    name: 'Walnusskerne',
    syn: ['Walnüsse', 'Walnuss', 'Walnusskern', 'Walnusshälften'],
    aisle: 'fruehstueck',
    bls: 'H120100',
    g: { stueck: 5, handvoll: 30, el: 8 },
    sell: { unit: 'packung', g: 200 },
  },
  {
    id: 'pistazie',
    name: 'Pistazienkerne',
    syn: [
      'Pistazien',
      'Pistazie',
      'Pistazienkern',
      'Pistazien geröstet und gesalzen',
    ],
    aisle: 'fruehstueck',
    bls: 'H250100',
    g: { el: 8, handvoll: 30 },
    sell: { unit: 'packung', g: 125 },
  },
  {
    id: 'mandeln',
    name: 'Mandeln',
    syn: [
      'Mandelkerne',
      'gehobelte Mandeln',
      'Mandelblättchen',
      'gemahlene Mandeln',
      'Mandel',
      'Mandelstifte',
    ],
    aisle: 'fruehstueck',
    bls: 'H210100',
    g: { stueck: 1.2, el: 8, handvoll: 30 },
    sell: { unit: 'packung', g: 200 },
  },
  {
    id: 'haselnuss',
    name: 'Haselnüsse',
    syn: ['Haselnusskerne', 'Haselnuss', 'gemahlene Haselnüsse'],
    aisle: 'fruehstueck',
    bls: 'H130100',
    g: { el: 8, handvoll: 30 },
    sell: { unit: 'packung', g: 200 },
  },
  {
    id: 'cashew',
    name: 'Cashewkerne',
    syn: ['Cashews', 'Cashewnüsse', 'Cashew'],
    aisle: 'fruehstueck',
    bls: 'H170100',
    g: { el: 9, handvoll: 30 },
    sell: { unit: 'packung', g: 200 },
  },
  {
    id: 'erdnuesse',
    name: 'Erdnüsse',
    syn: ['Erdnusskerne', 'geröstete Erdnüsse', 'Erdnuss'],
    aisle: 'fruehstueck',
    bls: 'H110600',
    g: { el: 9, handvoll: 30 },
    sell: { unit: 'packung', g: 200 },
  },
  {
    id: 'pinienkerne',
    name: 'Pinienkerne',
    syn: ['Pinienkern'],
    aisle: 'fruehstueck',
    bls: 'H320100',
    g: { el: 10, tl: 3 },
    sell: { unit: 'packung', g: 50 },
  },
  {
    id: 'sonnenblumenkerne',
    name: 'Sonnenblumenkerne',
    aisle: 'fruehstueck',
    bls: 'H430100',
    g: { el: 10, handvoll: 30 },
    sell: { unit: 'packung', g: 200 },
  },
  {
    id: 'kuerbiskerne',
    name: 'Kürbiskerne',
    aisle: 'fruehstueck',
    bls: 'H310100',
    g: { el: 10, handvoll: 30 },
    sell: { unit: 'packung', g: 200 },
  },
  {
    id: 'sesam',
    name: 'Sesam',
    syn: ['Sesamsaat', 'Sesamkörner', 'heller Sesam', 'schwarzer Sesam'],
    aisle: 'fruehstueck',
    bls: 'H420100',
    g: { el: 9, tl: 3 },
    sell: { unit: 'packung', g: 100 },
  },
  {
    id: 'leinsamen',
    name: 'Leinsamen',
    syn: ['geschroteter Leinsamen'],
    aisle: 'fruehstueck',
    bls: 'H410100',
    g: { el: 10, tl: 3 },
    sell: { unit: 'packung', g: 250 },
  },
  {
    id: 'chiasamen',
    name: 'Chiasamen',
    syn: ['Chia-Samen', 'Chia'],
    aisle: 'fruehstueck',
    bls: 'H480100',
    g: { el: 12, tl: 4 },
    sell: { unit: 'packung', g: 200 },
  },
  {
    id: 'schokolade',
    name: 'Zartbitterschokolade',
    syn: [
      'Schokolade',
      'Bitterschokolade',
      'Zartbitter',
      'Kuvertüre',
      'Zartbitterkuvertüre',
    ],
    aisle: 'fruehstueck',
    bls: 'S570000',
    g: { stueck: 5, tafel: 100 },
    sell: { unit: 'tafel', g: 100 },
  },

  // Tiefkühl
  {
    id: 'spinat-tk',
    name: 'TK-Spinat',
    syn: [
      'Spinat TK',
      'TK Spinat',
      'Blattspinat TK',
      'junger Spinat TK',
      'Spinat tiefgekühlt',
      'Rahmspinat',
      'Tiefkühlspinat',
    ],
    aisle: 'tiefkuehl',
    bls: 'G211200',
    sell: { unit: 'packung', g: 450 },
  },
  {
    id: 'erbsen-tk',
    name: 'TK-Erbsen',
    syn: [
      'Erbsen TK',
      'TK Erbsen',
      'Erbsen',
      'Erbsen tiefgekühlt',
      'junge Erbsen',
      'Erbse',
      'grüne Erbsen',
    ],
    aisle: 'tiefkuehl',
    bls: 'G760200',
    g: { el: 10, tasse: 140 },
    sell: { unit: 'packung', g: 450 },
  },
  {
    id: 'brechbohnen-tk',
    name: 'TK-Brechbohnen',
    syn: [
      'Brechbohnen TK',
      'TK Brechbohnen',
      'Brechbohnen',
      'grüne Bohnen TK',
      'Bohnen TK',
      'Brechbohnen tiefgekühlt',
    ],
    aisle: 'tiefkuehl',
    bls: 'G710200',
    sell: { unit: 'packung', g: 450 },
  },
  {
    id: 'petersilie-tk',
    name: 'TK-Petersilie',
    syn: ['Petersilie TK', 'TK Petersilie', 'Petersilie tiefgekühlt'],
    aisle: 'tiefkuehl',
    bls: 'G250100',
    g: { el: 4 },
    sell: { unit: 'packung', g: 50 },
  },
  {
    id: 'kraeuter-tk',
    name: 'TK-Kräuter',
    syn: [
      '8-Kräuter-Mischung',
      '8 Kräuter',
      'Kräuter TK',
      'TK Kräuter',
      'Kräutermischung TK',
      'Italienische Kräuter TK',
      'Tiefkühlkräuter',
      '8 Kräuter Mischung',
      '8-Kräuter',
    ],
    aisle: 'tiefkuehl',
    nutrition: false,
    g: { el: 4 },
    sell: { unit: 'packung', g: 50 },
  },
  {
    id: 'beeren-tk',
    name: 'TK-Beeren',
    syn: [
      'Beeren TK',
      'TK Beeren',
      'Tiefkühlbeeren',
      'TK-Beerenmischung',
      'Beerenmischung TK',
      'gefrorene Beeren',
    ],
    aisle: 'tiefkuehl',
    bls: 'F092100',
    g: { handvoll: 60 },
    sell: { unit: 'packung', g: 300 },
  },
  {
    id: 'gemuesemischung-tk',
    name: 'TK-Gemüsemischung',
    syn: [
      'Gemüsemischung TK',
      'TK Gemüse',
      'Pfannengemüse',
      'Tiefkühlgemüse',
      'Wokgemüse',
    ],
    aisle: 'tiefkuehl',
    bls: 'G992902',
    sell: { unit: 'packung', g: 750 },
  },

  // Getränke
  {
    id: 'wasser',
    name: 'Wasser',
    syn: [
      'Leitungswasser',
      'heißes Wasser',
      'kaltes Wasser',
      'Nudelwasser',
      'Spargelwasser',
      'Kochwasser',
      'lauwarmes Wasser',
      'Eiswasser',
    ],
    aisle: 'getraenke',
    nutrition: false,
    shopping: false,
    density: 1.0,
  },
  {
    id: 'weisswein',
    name: 'Weißwein',
    syn: ['trockener Weißwein', 'Weißwein trocken'],
    aisle: 'getraenke',
    bls: 'P210000',
    density: 1.0,
    sell: { unit: 'flasche', ml: 750 },
  },
  {
    id: 'rotwein',
    name: 'Rotwein',
    syn: ['trockener Rotwein', 'Rotwein trocken'],
    aisle: 'getraenke',
    bls: 'P2A3000',
    density: 1.0,
    sell: { unit: 'flasche', ml: 750 },
  },
  {
    id: 'orangensaft',
    name: 'Orangensaft',
    syn: ['O-Saft'],
    aisle: 'getraenke',
    bls: 'F603600',
    density: 1.04,
    sell: { unit: 'packung', ml: 1000 },
  },
  {
    id: 'apfelsaft',
    name: 'Apfelsaft',
    aisle: 'getraenke',
    bls: 'F110600',
    density: 1.04,
    sell: { unit: 'packung', ml: 1000 },
  },

  // Drogerie & Haushalt
  {
    id: 'backpapier',
    name: 'Backpapier',
    aisle: 'drogerie',
    nutrition: false,
    sell: { unit: 'rolle', g: 100 },
  },
  {
    id: 'schaschlikspiesse',
    name: 'Schaschlikspieß',
    plural: 'Schaschlikspieße',
    syn: ['Spieße', 'Holzspieße', 'Grillspieße', 'Holzspieß'],
    aisle: 'drogerie',
    nutrition: false,
    g: { stueck: 1 },
    sell: { unit: 'packung', pieces: 50 },
  },
  {
    id: 'mie-nudeln',
    name: 'Mie-Nudeln',
    syn: ['Mie Nudeln', 'Mienudeln', 'Asianudeln', 'Asia-Nudeln'],
    aisle: 'trocken',
    bls: 'E401000',
    sell: { unit: 'packung', g: 250 },
  },
  {
    id: 'glasnudeln',
    name: 'Glasnudeln',
    syn: ['Glasnudel'],
    aisle: 'trocken',
    bls: 'C559000',
    sell: { unit: 'packung', g: 200 },
  },
  {
    id: 'gewuerzgurken',
    name: 'Gewürzgurke',
    plural: 'Gewürzgurken',
    syn: [
      'Saure Gurken',
      'Saure Gurke',
      'Essiggurken',
      'Essiggurke',
      'Cornichons',
    ],
    aisle: 'konserven',
    bls: 'G890702',
    g: { stueck: 30 },
    sell: { unit: 'glas', g: 360 },
  },
  {
    id: 'limettensaft',
    name: 'Limettensaft',
    syn: ['Saft einer Limette'],
    aisle: 'wuerzen',
    bls: 'F602600',
    density: 1.03,
    g: { spritzer: 2, schuss: 10 },
    sell: { unit: 'flasche', ml: 200 },
  },
  {
    id: 'hefe',
    name: 'Hefe',
    aisle: 'backen',
    nutrition: false,
    g: { wuerfel: 42 },
  },
];
